import { prisma } from "@ibo/db";
import { Card, CardHeader, CardTitle } from "../../components/ui/card";
import { PostureIndicator } from "../../components/ui/posture-indicator";
import { PageHeader } from "../../components/ui/page-header";
import { EducationalDisclaimer } from "../../components/ui/educational-disclaimer";

export const dynamic = "force-dynamic";

export default async function PreMarketDigestPage() {
  const digest = await prisma.digest.findFirst({
    where: { digestType: "pre_market" },
    orderBy: { marketDate: "desc" },
    include: { sections: { orderBy: { sortOrder: "asc" } } },
  });

  const latestContext = await prisma.globalContextSnapshot.findFirst({
    orderBy: { date: "desc" },
  });

  return (
    <>
      <PageHeader
        title="Pre-Market Digest"
        description="Daily pre-market brief with global cues, FII/DII, and market posture"
      />
      <EducationalDisclaimer className="mb-4" />

      {/* Market Context */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Market Context</CardTitle>
        </CardHeader>
        {latestContext ? (
          <div className="space-y-3">
            <div className="flex items-center gap-4">
              <PostureIndicator
                posture={(latestContext.marketPosture ?? "mixed") as "favorable" | "mixed" | "hostile"}
                score={latestContext.postureScore ? Number(latestContext.postureScore) : 0}
              />
              <span className="text-sm text-slate-500">
                {latestContext.date.toLocaleDateString("en-IN", { dateStyle: "medium" })}
              </span>
            </div>
            <p className="whitespace-pre-line text-sm text-slate-600">{latestContext.narrative}</p>
          </div>
        ) : (
          <p className="text-sm text-slate-400">
            No market context data yet. The pre-market cron job runs at 8:30 AM IST.
          </p>
        )}
      </Card>

      {/* Digest Sections */}
      {digest ? (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-slate-800">
            {digest.title} — {digest.marketDate.toLocaleDateString("en-IN")}
          </h2>
          {digest.sections.map((section) => (
            <Card key={section.id}>
              <CardHeader>
                <CardTitle>{section.title}</CardTitle>
              </CardHeader>
              <div className="prose prose-sm prose-slate max-w-none">
                {section.bodyMarkdown}
              </div>
            </Card>
          ))}
        </div>
      ) : (
        <Card>
          <p className="text-sm text-slate-400">
            No pre-market digest available. Digests are auto-generated by the cron job at 8:30 AM IST.
          </p>
        </Card>
      )}
    </>
  );
}
