import { prisma } from "@ibo/db";
import { Card, CardHeader, CardTitle, CardDescription } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { PageHeader } from "../components/ui/page-header";

export const dynamic = "force-dynamic";

export default async function ReferencesPage() {
  const resources = await prisma.externalResource.findMany({
    orderBy: [{ category: "asc" }, { title: "asc" }],
  });

  const grouped = resources.reduce<Record<string, typeof resources>>((acc, row) => {
    if (!acc[row.category]) acc[row.category] = [];
    acc[row.category].push(row);
    return acc;
  }, {});

  return (
    <>
      <PageHeader
        title="Source References"
        description="Reference links for course context and market checks. Internal deterministic engines remain primary."
      />

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Reference Policy</CardTitle>
          <CardDescription>
            External resources are supporting references only. Signals and ranking are generated by internal rule engines.
          </CardDescription>
        </CardHeader>
      </Card>

      <div className="space-y-6">
        {Object.entries(grouped).map(([category, entries]) => (
          <Card key={category}>
            <CardHeader>
              <CardTitle className="capitalize">{category.replace(/_/g, " ")}</CardTitle>
              <CardDescription>{entries.length} references</CardDescription>
            </CardHeader>

            <ul className="space-y-2">
              {entries.map((entry) => (
                <li key={entry.key} className="rounded-lg border border-slate-100 p-3">
                  <div className="flex flex-wrap items-center gap-2">
                    <a
                      href={entry.url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-sm font-semibold text-brand-600 hover:underline"
                    >
                      {entry.title}
                    </a>
                    <Badge variant="muted">{entry.key}</Badge>
                    {entry.provider ? <Badge variant="default">{entry.provider}</Badge> : null}
                  </div>
                  {entry.notes ? <p className="mt-1 text-sm text-slate-600">{entry.notes}</p> : null}
                </li>
              ))}
            </ul>
          </Card>
        ))}
      </div>
    </>
  );
}
